language: php

# faster builds on docker-container setup
sudo: false

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: SYMFONY_VERSION=3.4.* COMPOSER_FLAGS='--prefer-lowest'
        - env: SYMFONY_VERSION=4.0.*

php:
    - 7.2

before_install:
    # disable xdebug since we don't use code-coverage for now
    - phpenv config-rm xdebug.ini
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
    - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: make tests
